Use datadog-agent/agent script for base

diff --git a/packaging/datadog-agent/osx/datadog-agent b/packaging/datadog-agent/osx/datadog-agent
--- a/packaging/datadog-agent/osx/datadog-agent
+++ b/packaging/datadog-agent/osx/datadog-agent
@@ -1,151 +1,143 @@
-#!/bin/sh
-PATH=$PATH:/sbin # add the location of start-stop-daemon on Debian
+#!/usr/bin/env sh
+BASEDIR=$(dirname $0)
+cd "$BASEDIR/.."
 
-AGENTPATH="/opt/datadog-agent/agent/agent.py"
-AGENTCONF="/etc/dd-agent/datadog.conf"
-DOGSTATSDPATH="/opt/datadog-agent/agent/dogstatsd.py"
-FORWARDERPATH="/opt/datadog-agent/agent/ddagent.py"
-NAME="datadog-agent"
-DESC="Datadog Agent"
-SUPERVISOR_PIDFILE="/var/run/datadog-supervisord.pid"
-SUPERVISOR_FILE="/etc/dd-agent/supervisor.conf"
-SUPERVISOR_SOCK="/var/tmp/datadog-supervisor.sock"
-SUPERVISORCTL_PATH="/opt/datadog-agent/bin/supervisorctl"
-SUPERVISORD_PATH="/opt/datadog-agent/bin/supervisord"
-SYSTEM_PATH=/opt/datadog-agent/embedded/bin:/opt/datadog-agent/bin:$PATH
+PATH=$BASEDIR/../venv/bin:$PATH
 
-if [ ! -x $AGENTPATH ]; then
-    echo "$AGENTPATH not found. Exiting."
-    exit 0
+SUPERVISOR_NOT_RUNNING="Supervisor is not running"
+SUPERVISOR_CONF_FILE='/etc/dd-agent/supervisord.conf'
+SOCK_FILE='/tmp/agent-supervisor.sock'
+PID_FILE='/tmp/supervisord.pid'
+action=$1
+
+if [ ! -n "$action" ]; then
+    action="start"
 fi
 
-check_status() {
-    # If the socket exists, we can use supervisorctl
-    if [ -e $SUPERVISOR_SOCK ]; then
-        # If we're using supervisor, check the number of datadog processes
-        # supervisor is currently controlling, and make sure that it's the
-        # same as the number of programs specified in the supervisor config
-        # file:
-
-        supervisor_processes=$($SUPERVISORCTL_PATH -c $SUPERVISOR_FILE status)
-        datadog_supervisor_processes=$(echo "$supervisor_processes" |
-                                       grep -v dogstatsd |
-                                       grep $NAME |
-                                       grep -c RUNNING)
-        supervisor_config_programs=$(grep -v dogstatsd $SUPERVISOR_FILE |
-                                     grep -c '\[program:')
-
-        if [ "$datadog_supervisor_processes" -ne "$supervisor_config_programs" ]; then
-            echo "$supervisor_processes"
-            echo "$DESC (supervisor) is NOT running all child processes"
-            return 1
-        else
-            echo "$DESC (supervisor) is running all child processes"
+supervisor_running() {
+    # Returns true if the supervisor is running, and false if not.
+    # We check if the supervisor is running by checking if
+    # SOCK_FILE exists, and if there is a PID file we also verify
+    # if the PID is in use.
+    if [ -e $SOCK_FILE -a -f $PID_FILE ]; then
+        pid=$(cat $PID_FILE)
+        if kill -0 $pid > /dev/null 2>&1; then
             return 0
         fi
+    fi
+    return 1
+}
+
+execute_if_supervisor_running() {
+    # Executes `supervisord -c $SUPERVISOR_CONF_FILE $*`
+    # if the supervisor is running.
+    if supervisor_running; then
+        supervisorctl -c $SUPERVISOR_CONF_FILE "$*"
+        return $?
     else
-        echo "$DESC (supervisor) is not running"
-        return 1
+        echo $SUPERVISOR_NOT_RUNNING
+        return 0
     fi
 }
 
-# Action to take
-case "$1" in
+check_agent_status() {
+
+
+    # First, we check if supervisor is running:
+    if ! supervisor_running; then
+        echo $SUPERVISOR_NOT_RUNNING
+        return 1
+    else
+        # Next, we check if supervisor is running all the datadog processes:
+
+        # Check the number of datadog processes supervisor is
+        # currently controlling, and make sure that it's the
+        # same as the number of programs specified in the
+        # supervisor config file:
+        status_output=$(supervisorctl -c $SUPERVISOR_CONF_FILE status)
+        datadog_supervisor_processes=$(echo "$status_output" |
+                                       grep 'datadog-agent' |
+                                       grep -c RUNNING)
+        supervisor_config_programs=$(cat $SUPERVISOR_CONF_FILE |
+                                     grep -c '\[program:')
+
+        echo "$status_output"
+        if [ "$datadog_supervisor_processes" -ne "$supervisor_config_programs" ]; then
+            echo "Supervisor is NOT running all child processes"
+            return 1
+        else
+            echo "Supervisor is running all child processes"
+            return 0
+        fi
+    fi
+}
+
+case $action in
     start)
-        if [ ! -f $AGENTCONF ]; then
-            echo "$AGENTCONF not found. Exiting."
-            exit 3
-        fi
-
-        check_status > /dev/null
-        if [ $? -eq 0 ]; then
-            echo "$DESC is already running"
+        if supervisor_running; then
+            echo "Supervisor is already running"
+            execute_if_supervisor_running start all
             exit 0
+        else
+            echo "Starting supervisor"
+            supervisord -c $SUPERVISOR_CONF_FILE
+            # Since the above command currently runs in the foreground, we don't
+            # have to worry about checking the status of the Agent and setting
+            # an exit code here.
         fi
-
-        $AGENTPATH configcheck > /dev/null
-        if [ $? -ne 0 ]; then
-            log_daemon_msg "Invalid check configuration. Please run sudo /usr/bin/datadog-agent configtest for more details."
-            log_daemon_msg "Resuming starting process."
-        fi
-
-
-        log_daemon_msg "Starting $DESC (using supervisord)" "$NAME"
-        PATH=$SYSTEM_PATH start-stop-daemon --start --quiet --oknodo --exec $SUPERVISORD_PATH -- -c $SUPERVISOR_FILE --pidfile $SUPERVISOR_PIDFILE
-        if [ $? -ne 0 ]; then
-            log_end_msg 1
-        fi
-
-        # check if the agent is running once per second for 10 seconds
-        retries=10
-        while [ $retries -gt 1 ]; do
-          if check_status > /dev/null; then
-              # We've started up successfully. Exit cleanly
-              log_end_msg 0
-              exit 0
-          else
-              retries=$(($retries - 1))
-              sleep 1
-          fi
-        done
-        # After 10 tries the agent didn't start. Report an error
-        log_end_msg 1
-        check_status # report what went wrong
-        $0 stop
-        exit 1
         ;;
+
     stop)
-
-        log_daemon_msg "Stopping $DESC (stopping supervisord)" "$NAME"
-        start-stop-daemon --stop --retry 30 --quiet --oknodo --pidfile $SUPERVISOR_PIDFILE
-
-        log_end_msg $?
-
-        ;;
-
-    info)
-        shift # Shift 'info' out of args so we can pass any
-              # addtional options to the real command
-              # (right now only dd-agent supports additional flags)
-        $AGENTPATH info $@
-        COLLECTOR_RETURN=$?
-        $DOGSTATSDPATH info
-        DOGSTATSD_RETURN=$?
-        $FORWARDERPATH info
-        FORWARDER_RETURN=$?
-        exit $(($COLLECTOR_RETURN+$DOGSTATSD_RETURN+$FORWARDER_RETURN))
-        ;;
-
-    status)
-        check_status
-        ;;
-
-    restart|force-reload)
-        $0 stop
-        $0 start
-        ;;
-
-    configcheck)
-        $AGENTPATH configcheck
+        execute_if_supervisor_running stop all
         exit $?
         ;;
 
-    configtest)
-        $AGENTPATH configcheck
+    restart)
+        # FIXME: This command won't do anything if the supervisor isn't running.
+        # The restart command should just call stop and then start so it doesn't
+        # rely on the supervisor running. Once we stop starting the Agent in the
+        # foreground we should fix this.
+        execute_if_supervisor_running restart all
+        exit $?
+        ;;
+
+    status)
+        check_agent_status
+        exit $?
+        ;;
+
+    info)
+        shift # shift to pass the remaining arguments to agent/agent.py info.
+              # Currently only agent.py takes additional arguments
+        python agent/agent.py info $@
+        RETURN_VALUE=$?
+        python agent/dogstatsd.py info
+        RETURN_VALUE=$(($RETURN_VALUE || $?))
+        python agent/ddagent.py info
+        RETURN_VALUE=$(($RETURN_VALUE || $?))
+        exit $RETURN_VALUE
+        ;;
+
+    configcheck)
+        python agent/agent.py configcheck
+        exit $?
+        ;;
+
+    check)
+        shift
+        python agent/agent.py check $@
         exit $?
         ;;
 
     jmx)
         shift
-        $AGENTPATH jmx $@
+        python agent/agent.py jmx $@
         exit $?
         ;;
 
     *)
-        N=/etc/init.d/$NAME
-        echo "Usage: $N {start|stop|restart|info|status|configcheck|configtest|jmx}"
-        exit 1
+        echo "Usage: $0 {start|stop|restart|info|status|configcheck|check|jmx}"
+        exit 2
         ;;
 esac
 
-exit $?
